# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhs', '0004_auto_20160130_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='lat_long',
        ),
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
